export const ALBUM_CONFIG = {
  totalStickers: 708,
  categories: [
    { id: 'verein', group: 'fussball', name: 'Verein (SV Dalum)', shortName: 'Verein', range: [1, 1] },
    { id: 'fussball-g1', group: 'fussball', name: 'Fussball G1-Junioren', shortName: 'FB G1', range: [2, 25] },
    { id: 'fussball-g2', group: 'fussball', name: 'Fussball G2-Junioren', shortName: 'FB G2', range: [26, 58] },
    { id: 'fussball-g3', group: 'fussball', name: 'Fussball G3-Junioren', shortName: 'FB G3', range: [59, 82] },
    { id: 'fussball-f-juniorinnen', group: 'fussball', name: 'Fussball F-Juniorinnen', shortName: 'FB F-Jun.', range: [83, 100] },
    { id: 'fussball-f1', group: 'fussball', name: 'Fussball F1-Junioren', shortName: 'FB F1', range: [101, 117] },
    { id: 'fussball-f2', group: 'fussball', name: 'Fussball F2-Junioren', shortName: 'FB F2', range: [118, 140] },
    { id: 'fussball-e1', group: 'fussball', name: 'Fussball E1-Junioren', shortName: 'FB E1', range: [141, 161] },
    { id: 'fussball-e2', group: 'fussball', name: 'Fussball E2-Junioren', shortName: 'FB E2', range: [162, 180] },
    { id: 'fussball-d2', group: 'fussball', name: 'Fussball D2-Junioren', shortName: 'FB D2', range: [181, 186] },
    { id: 'fussball-d3', group: 'fussball', name: 'Fussball D3-Junioren', shortName: 'FB D3', range: [187, 204] },
    { id: 'fussball-c1', group: 'fussball', name: 'Fussball C1-Junioren', shortName: 'FB C1', range: [205, 224] },
    { id: 'fussball-c2', group: 'fussball', name: 'Fussball C2-Junioren', shortName: 'FB C2', range: [225, 228] },
    { id: 'fussball-b1', group: 'fussball', name: 'Fussball B1-Junioren', shortName: 'FB B1', range: [229, 250] },
    { id: 'fussball-a-juniorinnen', group: 'fussball', name: 'Fussball A-Juniorinnen', shortName: 'FB A-Jun.', range: [251, 265] },
    { id: 'fussball-a-junioren', group: 'fussball', name: 'Fussball A-Junioren', shortName: 'FB A1', range: [266, 283] },
    { id: 'fussball-1-herren', group: 'fussball', name: 'Fussball 1. Herren', shortName: 'FB 1. Herren', range: [284, 315] },
    { id: 'fussball-2-herren', group: 'fussball', name: 'Fussball 2. Herren', shortName: 'FB 2. Herren', range: [316, 345] },
    { id: 'fussball-ue32', group: 'fussball', name: 'Fussball Ue32', shortName: 'FB Ue32', range: [346, 368] },
    { id: 'fussball-ue40', group: 'fussball', name: 'Fussball Ue40', shortName: 'FB Ue40', range: [369, 388] },
    { id: 'walking-football', group: 'fussball', name: 'Walking Football', shortName: 'Walking', range: [389, 403] },
    { id: 'fussball-schiedsrichter', group: 'fussball', name: 'Fussball Schiedsrichter', shortName: 'FB Schiri', range: [404, 407] },
    { id: 'handball-g-jugend-minis', group: 'handball', name: 'Handball G-Jugend Minis', shortName: 'HB Minis', range: [408, 424] },
    { id: 'handball-f-jugend', group: 'handball', name: 'Handball F-Jugend', shortName: 'HB F', range: [425, 447] },
    { id: 'handball-e-jugend', group: 'handball', name: 'Handball E-Jugend', shortName: 'HB E', range: [448, 472] },
    { id: 'handball-weibliche-d', group: 'handball', name: 'Handball weibliche D-Jugend', shortName: 'HB wD', range: [473, 491] },
    { id: 'handball-maennliche-d', group: 'handball', name: 'Handball maennliche D-Jugend', shortName: 'HB mD', range: [492, 510] },
    { id: 'handball-weibliche-c', group: 'handball', name: 'Handball weibliche C-Jugend', shortName: 'HB wC', range: [511, 535] },
    { id: 'handball-weibliche-b', group: 'handball', name: 'Handball weibliche B-Jugend', shortName: 'HB wB', range: [536, 553] },
    { id: 'handball-weibliche-a', group: 'handball', name: 'Handball weibliche A-Jugend', shortName: 'HB wA', range: [554, 566] },
    { id: 'handball-1-damen', group: 'handball', name: 'Handball 1. Damen', shortName: 'HB 1. Damen', range: [567, 589] },
    { id: 'handball-2-damen', group: 'handball', name: 'Handball 2. Damen', shortName: 'HB 2. Damen', range: [590, 613] },
    { id: 'handball-1-herren', group: 'handball', name: 'Handball 1. Herren', shortName: 'HB 1. Herren', range: [614, 630] },
    { id: 'handball-2-herren', group: 'handball', name: 'Handball 2. Herren', shortName: 'HB 2. Herren', range: [631, 647] },
    { id: 'handball-schiedsrichter', group: 'handball', name: 'Handball Schiedsrichter', shortName: 'HB Schiri', range: [648, 654] },
    { id: 'orga-kinderturnen', group: 'weitere', name: 'Orga Kinderturnen', shortName: 'Kinderturnen', range: [655, 663] },
    { id: 'tischtennis-1', group: 'weitere', name: 'Tischtennis 1. Mannschaft', shortName: 'TT 1.', range: [664, 669] },
    { id: 'dart', group: 'weitere', name: 'Dart', shortName: 'Dart', range: [670, 679] },
    { id: 'volleyball', group: 'weitere', name: 'Volleyball', shortName: 'Volleyball', range: [680, 691] },
    { id: 'organisation', group: 'weitere', name: 'Organisation', shortName: 'Orga', range: [692, 700] },
    { id: 'vorstand', group: 'weitere', name: 'Vorstand', shortName: 'Vorstand', range: [701, 707] },
    { id: 'stickerfreunde', group: 'weitere', name: 'Stickerfreunde', shortName: 'Freunde', range: [708, 708] },
  ],
}

export function getCategoryForSticker(number) {
  return ALBUM_CONFIG.categories.find(
    (category) => number >= category.range[0] && number <= category.range[1]
  )
}
